spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动类（保持不变）
    url: jdbc:mysql://hybrid01:3305/metadata  # 修正为 mariadb 前缀
    username: work  # 基础属性移至 datasource 层级
    password: "@666"  # 基础属性移至 datasource 层级
    hikari:
server:
  port: 8112                       # 单点登录服务端口
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  forward-headers-strategy: framework
sdp:
  api-domain: http://hybrid01
  api-key: $666666

sensors:
  conf:
    send_metrics: false
  login:
    checkToken: true                # 是否通过点击 url ，传递 token 进行单点登录
    checkPassword: true            # 是否开启通过页面输入用户名密码进行验证登录，默认false，为不开启
    error: false                    # 如果发生异常是否跳转到指定地址，如果为true，需设置errorUrl配置项
    errorUrl: null                  # 发生异常时跳转地址(样例：http://ip地址:8107/sa)
    #successUrl:                    # (可选)登录成功后，页面重定向的地址(样例：/segmentation 或者 http://ip地址:8107/segmentation/ )
    defaultProjectName: production  # 默认登录的项目，需要是神策系统中实际存在的项目
    defaultRole: guest            # 登录默认的角色
#
saml2:
  metadata-url: https://{{.EntityID}}/saml/metadata.xml          # IDP metadata 路径 # IDP metadata 路径
  sp-metadata-url: /sensorsdata/main/dingkai/program/dk_sso/sso/conf/saml/sp_metadata.xml
  entityId: {{.EntityID}}
  hostname: {{.EntityID}}                                              # 请求域名 domain
  protocol: https                                                                        # HTTP Method
  storeFilePath: saml/sensorsKeystore.jks                                       # jks 文件路径
  storepass: 2wsx#EDC                                                                    # jks storepass
  keypass: 3edc$RFV                                                                      # jks keypass
  alias: sensorskey                                                                      # jks alias

