# source相关配置
source:
  kafka:
    servers: hybrid01.classic-tx-beijing-01.fuzhou-test.deploy.sensorsdata.cloud:9092
    topic: [ event_topic ]
    group: sdd_kafuka_data_subscribe
    reset: earliest
    covering_offset: false

# sink相关的配置
sink:
  kafka:
    servers: &sink-kafka 10.129.20.17:9992
    topic: [ event-topic ]
    properties:
      'transaction.timeout.ms': 900000
      # 添加安全认证参数（根据实际认证机制调整）
      'security.protocol': 'SASL_PLAINTEXT'  # 安全协议
      'sasl.mechanism': 'PLAIN'              # 认证机制
      'sasl.jaas.config': 'org.apache.kafka.common.security.plain.PlainLoginModule required username="ice" password="ice@666";'
  fail:
    kafka:
      servers: *sink-kafka
      topic: [ export_invalid_topic ]
      properties:
        'transaction.timeout.ms': 900000
        # 失败 Sink 同样需要安全认证参数（与主 Sink 保持一致）
        'security.protocol': 'SASL_PLAINTEXT'  # 安全协议
        'sasl.mechanism': 'PLAIN'              # 认证机制
        'sasl.jaas.config': 'org.apache.kafka.common.security.plain.PlainLoginModule required username="ice" password="ice@666";'


# topic 映射关系
sink-topic:
  event_topic: event-topic

# 需要过滤的type类型
filter.type: watermark

# 默认并行度
parallelism:
  default: 3

conf:
  port: 10104
  checkpoint:
    interval: 60000
