server:
  port: 9730

system:
  request:
    super_token:
    domain:
    api_key:
    org_id:
  profile:
    batch-size: 10000
    operation-code: "77777"
    user-filed: "identity_user_id"

feishu:
  webhookUrl:
  msg_type:
  secret:
  card:
    type:
    template_id:
    template_version_name: