server:
  port: 9730

system:
  request:
    super_token:
    domain: http://meta01:8107
    api_key:
    org_id:
  profile:
    batch-size: 10000
    operation-code: "98206"
    username: "user_tag_xm"
    user-filed: "identity_user_id"
feishu:
  webhookUrl:
  msg_type:
  secret:
  card:
    type:
    template_id:
    template_version_name:

spring:
  devtools:
    add-properties: false